In [ ]:
import tweepy
import csv
import pandas as pd
import sys
import numpy as np

In [ ]:
from importlib import reload
reload(sys)

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

In [ ]:
#### input your credentials here
consumer_key = 'CQldZWCZjOPCmcuggVEYDLKb8'
consumer_secret = 'rVGwBrR5PKxZs2yIpwPIbLP6TzhARo7C4cRodrCKVFSEGTOOWi'
access_token = '1506450127057305604-XjukkZt3QPyCQ8oZTRC4qpQnglQu4u'
access_token_secret = 'xY7v8pWdKZaQcGGVokNQIwgwoiMSlmZlbn6nWAaytJxN2'
auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)
api = tweepy.API(auth, wait_on_rate_limit = True)

testing

In [ ]:
# Load dataset
def load_data():
    data = pd.read_csv("gdrive/My Drive/Colab Notebooks/srilanka_easter.csv")
    data.columns = data.columns.str.replace(' ','_')
    return data

In [ ]:
tweet_df = load_data()
tweet_df.head(2)

,Tweet_Id,Tweet_URL,Tweet_Posted_Time_(UTC),Tweet_Content,Tweet_Type,Client,Retweets_Received,Favourites_Received,Tweet_Location,Tweet_Language,...,Screen_Name,User_Bio,Verified_or_Non-Verified,Profile_URL,Protected_or_Non-protected,User_Followers,User_Following,Favourites_Count,Statuses_Count,User_Account_Creation_Date
0,"""1130420279627395072""",https://twitter.com/HotelierME/status/11304202...,20 May 2019 10:29:31,#SriLanka #hotel occupancy drops following #Ea...,Tweet,Fanbooster by Traject,0,0,United Arab Emirates,English,...,HotelierME,The online home for hospitality industry profe...,Non-Verified,https://twitter.com/HotelierME,Non-Protected,15335,4,1380,43301,03 Mar 2009 06:39:39
1,"""1130150275766001664""",https://twitter.com/ImtiazsharPYO/status/11301...,19 May 2019 16:36:37,RT @BBhuttoZardari: Devastating news coming ou...,ReTweet,Twitter for Android,0,0,"Sindh, Pakistan",English,...,ImtiazsharPYO,"Hi I'am #imtiaz_Shar From Sindh,Pakistan.\nI s...",Non-Verified,https://twitter.com/ImtiazsharPYO,Non-Protected,5255,389,173770,31589,19 Apr 2012 16:08:34

In [ ]:
pattern='Colombo,Sri Lanka |Colombo, Sri Lanka|Sri Lanka| Srilanka ðŸ‡±ðŸ‡° |Colombo|Colombo, Srilanka|Colombo Sri Lanka|Sri Lankan'

mask=tweet_df['Tweet_Location'].str.contains(pattern,case=False,na=False)
tweet_df1=tweet_df[mask]
tweet_df1

,Tweet_Id,Tweet_URL,Tweet_Posted_Time_(UTC),Tweet_Content,Tweet_Type,Client,Retweets_Received,Favourites_Received,Tweet_Location,Tweet_Language,...,Screen_Name,User_Bio,Verified_or_Non-Verified,Profile_URL,Protected_or_Non-protected,User_Followers,User_Following,Favourites_Count,Statuses_Count,User_Account_Creation_Date
3,"""1130097107333836800""",https://twitter.com/ChandaniKirinde/status/113...,19 May 2019 13:05:21,"RT @vipulananda: #IS didn’t choose #SriLanka, ...",ReTweet,Twitter for iPhone,0,0,"Colombo,Sri Lanka",English,...,ChandaniKirinde,Journalist. Views my own.,Non-Verified,https://twitter.com/ChandaniKirinde,Non-Protected,11043,1365,38397,49764,10 Oct 2013 06:53:14
4,"""1130043387724353536""",https://twitter.com/vipulananda/status/1130043...,19 May 2019 09:31:53,"#IS didn’t choose #SriLanka, but Lankan group ...",Tweet,Twitter for iPhone,1,4,"Colombo, Sri Lanka",English,...,vipulananda,விபுலானந்தா විපුල් | Journalist | Editor | Act...,Non-Verified,https://twitter.com/vipulananda,Non-Protected,3053,5001,118806,122186,03 Nov 2007 07:37:38
10,"""1129755645698297857""",https://twitter.com/vipulananda/status/1129755...,18 May 2019 14:28:30,'Virulent #Buddhist #nationalism that fueled a...,Tweet,Twitter Web App,0,0,"Colombo, Sri Lanka",English,...,vipulananda,விபுலானந்தா විපුල් | Journalist | Editor | Act...,Non-Verified,https://twitter.com/vipulananda,Non-Protected,3053,5001,118806,122186,03 Nov 2007 07:37:38
13,"""1129449756512727040""",https://twitter.com/vipulananda/status/1129449...,17 May 2019 18:13:00,#SriLanka people pray during Friday noon praye...,Tweet,Twitter Web App,1,0,"Colombo, Sri Lanka",English,...,vipulananda,விபுலானந்தா විපුල් | Journalist | Editor | Act...,Non-Verified,https://twitter.com/vipulananda,Non-Protected,3053,5001,118806,122186,03 Nov 2007 07:37:38
14,"""1129435664393691138""",https://twitter.com/vipulananda/status/1129435...,17 May 2019 17:17:00,#Opinion | #SriLanka is burning — again https:...,Tweet,Twitter Web Client,0,1,"Colombo, Sri Lanka",English,...,vipulananda,விபுலானந்தா විපුල් | Journalist | Editor | Act...,Non-Verified,https://twitter.com/vipulananda,Non-Protected,3053,5001,118806,122186,03 Nov 2007 07:37:38
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10952,"""1119811434756673536""",https://twitter.com/MarieszCader/status/111981...,21 Apr 2019 03:53:45,Here's Wishing All Family and Friends A Very H...,Tweet,Instagram,0,0,Sri Lanka,English,...,MarieszCader,Singer\nSongwriter\nEvent Manager\nEntrepreneu...,Non-Verified,https://twitter.com/MarieszCader,Non-Protected,153,750,2514,2986,03 Sep 2016 07:22:52
10953,"""1119811161405448192""",https://twitter.com/EmbarkLK/status/1119811161...,21 Apr 2019 03:52:40,Have an egg-cellent Easter everyone! 🐰\n\n#emb...,Tweet,Twitter for iPhone,0,3,Sri Lanka,English,...,EmbarkLK,Transforming the lives of street dogs in Sri L...,Non-Verified,https://twitter.com/EmbarkLK,Non-Protected,9652,86,849,8312,29 Dec 2009 10:21:51
10954,"""1119810080554344448""",https://twitter.com/anp66/status/1119810080554...,21 Apr 2019 03:48:22,Blast near Kochchikade Church and casualties r...,Tweet,Twitter for iPhone,0,0,"Colombo , Sri Lanka",English,...,anp66,Journalist/CEO &amp; Founder of #PetTalk/Entre...,Non-Verified,https://twitter.com/anp66,Non-Protected,1734,1150,1217,9871,08 Jan 2011 13:53:27
10955,"""1119809906729717761""",https://twitter.com/PrishanPhoto/status/111980...,21 Apr 2019 03:47:41,Have a blessed Easter #easter #prishan #prisha...,Tweet,IFTTT,0,0,Sri Lanka,English,...,PrishanPhoto,Professional Portrait &amp; Commercial Photogr...,Non-Verified,https://twitter.com/PrishanPhoto,Non-Protected,845,1980,169,3395,06 Aug 2009 16:40:19
10957,"""1119792187993206784""",https://twitter.com/MFA_SriLanka/status/111979...,21 Apr 2019 02:37:17,We wish all Christians in #SriLanka and around...,Tweet,Twitter Web Client,21,51,"Colombo, Sri Lanka",English,...,MFA_SriLanka,Official Twitter Account of the Foreign Minist...,Verified,https://twitter.com/MFA_SriLanka,Non-Protected,35016,590,1131,5638,08 May 2013 04:37:44

In [ ]:
model_1_dataset3=tweet_df1.drop_duplicates(subset=['Screen_Name'])

In [ ]:
model_1_dataset3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 125 entries, 3 to 10957
Data columns (total 22 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Tweet_Id                    125 non-null    object
 1   Tweet_URL                   125 non-null    object
 2   Tweet_Posted_Time_(UTC)     125 non-null    object
 3   Tweet_Content               125 non-null    object
 4   Tweet_Type                  125 non-null    object
 5   Client                      125 non-null    object
 6   Retweets_Received           125 non-null    int64
 7   Favourites_Received         125 non-null    int64
 8   Tweet_Location              125 non-null    object
 9   Tweet_Language              124 non-null    object
 10  User_Id                     125 non-null    object
 11  Name                        125 non-null    object
 12  Screen_Name                 125 non-null    object
 13  User_Bio                    117 non-null    object
 14  Verified_or_Non-Verified    125 non-null    object
 15  Profile_URL                 125 non-null    object
 16  Protected_or_Non-protected  125 non-null    object
 17  User_Followers              125 non-null    int64
 18  User_Following              125 non-null    int64
 19  Favourites_Count            125 non-null    int64
 20  Statuses_Count              125 non-null    int64
 21  User_Account_Creation_Date  125 non-null    object
dtypes: int64(6), object(16)
memory usage: 22.5+ KB

In [ ]:
model_1_result=model_1_dataset3[['User_Id', 'Name','Screen_Name']].copy()
model_1_result['User_Id_punct'] = model_1_result['User_Id'].apply(lambda x: x.replace('"', ''))
model_1_result.head()
model_1_dataset2=model_1_result[['User_Id_punct', 'Name','Screen_Name']].copy()
model_1_dataset2.rename(columns = {'User_Id_punct':'User_Id'}, inplace = True)
model_1_dataset2.head(10)
#model_1_dataset1=model_1_dataset3['Screen_Name'].head(10)

                 User_Id                 Name      Screen_Name
3             1951067186  Chandani Kirinde 🇱🇰  ChandaniKirinde
4                9909452       Vipulananda 🇱🇰      vipulananda
15    957681564284006401       Asiri Fernando  AsiriFernandoLK
21   1100241609721958400          Lankanenews      lankanenews
22            1869917396    Wasitha Pinnawala   WasithaKeminda
26            4611985095           MarcMartín      MarcMartinn
28             122884856       Lankanorg News        LankanOrg
37              40320649              neetwit          Neetwit
163            301807277         Francanstyle     Francanstyle
235            114960150              Vikalpa    vikalpavoices

In [ ]:
tweet_df = load_data()
tweet_df.head(2)


#li = ['Colombo,Sri Lanka', 'Sri Lanka', 'Colombo, Sri Lanka',]
 
pattern='Colombo,Sri Lanka |Colombo, Sri Lanka|Sri Lanka| Srilanka ðŸ‡±ðŸ‡° |Colombo|Colombo, Srilanka|Colombo Sri Lanka|Sri Lankan'

mask=tweet_df['Tweet_Location'].str.contains(pattern,case=False,na=False)
tweet_df1=tweet_df[mask]
tweet_df1

import json
col_list = tweet_df1.Screen_Name.values.tolist()
col_list

json_str = json.dumps(col_list)
json_str

a=col_list.replace("'", '"')
a



for user in json_str:
  users = api.lookup_users(screen_names =user)

  for user in users:
    print(user.screen_name, user.created_at,user.statuses_count, user.followers_count, user.friends_count, user.verified, 
user.location, user.listed_count,user.id,user.name)

AttributeError: ignored

In [ ]:
my_str = "bobby 'hadz' com"

result = my_str.replace("'", '"')
print(result) # 👉️ bobby "hadz" com

bobby "hadz" com

In [ ]:
csvFile = open('users.csv', 'a')
csvWriter = csv.writer(csvFile)
csvWriter.writerow(["screen_name", "created_at", "statuses_count", "followers_count", "friends_count", "verified", 
"location", "listed_count"])

100

In [ ]:
my_list = ['one', 'two', 'three']

my_str = ', '.join(f'"{item}"' for item in my_list)

print(my_str)

"one", "two", "three"

In [ ]:
root_path = 'gdrive/My Drive/Colab Notebooks/'

In [ ]:
with open('gdrive/My Drive/Colab Notebooks/usernames.txt', 'r') as f:    
   text=f.read()
vocab = sorted(set(text)) 
vocab_to_int = {c: i for i, c in enumerate(vocab)}    
int_to_vocab = dict(enumerate(vocab))    
encoded = np.array([vocab_to_int[c] for c in text], dtype=np.int32)

In [2]:
#users = ["BBCWorld","AzzamAmeen","SriLankaTweet","adaderana","NewsFirstSL","DailyNews_lk","MarianneDavid24","HarshadeSilvaMP","RiviraNews","Dailymirror_SL"] 

users = api.lookup_users(screen_names =["dula_aluthge"])
                         
                         
                         ["ChandaniKirinde","vipulananda","AsiriFernandoLK","lankanenews","WasithaKeminda","MarcMartinn","LankanOrg","Neetwit","Francanstyle","vikalpavoices"])
dula_aluthge
users.info()

NameError: ignored

In [ ]:
import pandas as pd
#df = pd.DataFrame(list)

In [ ]:
for user in users:
  print(user.screen_name, user.created_at, 
        user.statuses_count, user.followers_count, user.friends_count, user.verified, 
user.location, user.listed_count,user.id,user.name)

ChandaniKirinde 2013-10-10 06:53:14 50061 11129 1392 False Colombo,Sri Lanka 152 1951067186 Chandani Kirinde 🇱🇰
vipulananda 2007-11-03 07:37:38 124277 3046 5000 False Colombo, Sri Lanka 353 9909452 Vipulananda 🇱🇰
AsiriFernandoLK 2018-01-28 18:27:32 17718 1207 2119 False Sri Lanka 23 957681564284006401 Asiri Fernando
lankanenews 2019-02-26 03:50:16 3123 597 1784 False Sri Lanka 0 1100241609721958400 Lankanenews
WasithaKeminda 2013-09-16 02:07:12 80 337 546 False Pinnawala 0 1869917396 Wasitha Pinnawala
MarcMartinn 2015-12-26 15:30:38 1820 57 155 False Sri Lanka 0 4611985095 MarcMartín
LankanOrg 2010-03-14 06:54:48 6430 140 574 False Sri Lanka 0 122884856 Lankanorg News
Neetwit 2009-05-15 20:06:00 191839 2934 2867 False Colombo 15 40320649 neetwit
Francanstyle 2011-05-20 03:02:43 1611 81 347 False Sri Lanka 0 301807277 Francanstyle
vikalpavoices 2010-02-17 04:34:35 35414 16105 151 True Colombo, Srilanka 143 114960150 Vikalpa

In [ ]:
for user in users:
  print(user.screen_name, user.created_at, 
        user.statuses_count, user.followers_count, user.friends_count, user.verified, 
user.location, user.listed_count,user.id,user.name)

list = []
for user in users:
    #text = user._json["full_text"]

    refined_tweet = {'screen_name' : user.screen_name,
                     'User_Id' : user.id,
                     'Name':user.name,
                    'followers_count' : user.followers_count,
                    'friends_count' : user.friends_count,
                    'created_at' : user.created_at,
                    'statuses_count' : user.statuses_count,
                    'listed_count' : user.listed_count, 
                    'location' : user.location,
                    'verified' : user.verified,
                     'User_Bio':user.description}
    
    list.append(refined_tweet)




#csvWriter.writerow([user.screen_name, user.created_at, user.statuses_count, user.followers_count, user.friends_count, 
#user.verified, user.location, user.listed_count])

ChandaniKirinde 2013-10-10 06:53:14 50061 11129 1392 False Colombo,Sri Lanka 152 1951067186 Chandani Kirinde 🇱🇰
vipulananda 2007-11-03 07:37:38 124277 3046 5000 False Colombo, Sri Lanka 353 9909452 Vipulananda 🇱🇰
AsiriFernandoLK 2018-01-28 18:27:32 17718 1207 2119 False Sri Lanka 0 957681564284006401 Asiri Fernando
lankanenews 2019-02-26 03:50:16 3123 597 1784 False Sri Lanka 0 1100241609721958400 Lankanenews
WasithaKeminda 2013-09-16 02:07:12 80 337 546 False Pinnawala 0 1869917396 Wasitha Pinnawala
MarcMartinn 2015-12-26 15:30:38 1820 57 155 False Sri Lanka 0 4611985095 MarcMartín
LankanOrg 2010-03-14 06:54:48 6430 140 574 False Sri Lanka 0 122884856 Lankanorg News
Neetwit 2009-05-15 20:06:00 191839 2934 2867 False Colombo 15 40320649 neetwit
Francanstyle 2011-05-20 03:02:43 1611 81 347 False Sri Lanka 1 301807277 Francanstyle
vikalpavoices 2010-02-17 04:34:35 35414 16105 151 True Colombo, Srilanka 143 114960150 Vikalpa

In [ ]:
import pandas as pd
df = pd.DataFrame(list)

In [ ]:
df

,screen_name,User_Id,Name,followers_count,friends_count,created_at,statuses_count,listed_count,location,verified,User_Bio
0,ChandaniKirinde,1951067186,Chandani Kirinde 🇱🇰,11129,1392,2013-10-10 06:53:14,50061,152,"Colombo,Sri Lanka",False,Journalist. Views my own.
1,vipulananda,9909452,Vipulananda 🇱🇰,3046,5000,2007-11-03 07:37:38,124277,353,"Colombo, Sri Lanka",False,விபுலானந்தா විපුල් | Journalist | Editor | Act...
2,AsiriFernandoLK,957681564284006401,Asiri Fernando,1207,2119,2018-01-28 18:27:32,17718,0,Sri Lanka,False,Journalist | News Editor | 🇱🇰 | Interested in;...
3,lankanenews,1100241609721958400,Lankanenews,597,1784,2019-02-26 03:50:16,3123,0,Sri Lanka,False,සත්‍ය වළලන්නට පෙර
4,WasithaKeminda,1869917396,Wasitha Pinnawala,337,546,2013-09-16 02:07:12,80,0,Pinnawala,False,
5,MarcMartinn,4611985095,MarcMartín,57,155,2015-12-26 15:30:38,1820,0,Sri Lanka,False,
6,LankanOrg,122884856,Lankanorg News,140,574,2010-03-14 06:54:48,6430,0,Sri Lanka,False,#SriLanka and worldwide #News in English Sport...
7,Neetwit,40320649,neetwit,2934,2867,2009-05-15 20:06:00,191839,15,Colombo,False,against deception of public with fabricated li...
8,Francanstyle,301807277,Francanstyle,81,347,2011-05-20 03:02:43,1611,1,Sri Lanka,False,Nothing did I bring...none will be taken...
9,vikalpavoices,114960150,Vikalpa,16105,151,2010-02-17 04:34:35,35414,143,"Colombo, Srilanka",True,"Citizen Journalism website in Sinhala, from Sr..."

In [ ]:
csvWriter.writerow([user.screen_name, user.created_at, user.statuses_count, user.followers_count, user.friends_count, 
user.verified, user.location, user.listed_count])



import pandas as pd

df.to_csv('df',sep='\t')
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

uploaded = drive.CreateFile({'title': 'sample.csv', 'mimeType':'csv'})
uploaded.SetContentFile('abc')
uploaded.Upload()

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

In [ ]:
root_path = 'gdrive/My Drive/Colab Notebooks/'

In [ ]:
df.to_csv('ordinary.csv')

In [ ]:
!cp data.csv "gdrive/My Drive/Colab Notebooks/"

In [ ]:

# import the module
import tweepy
  
# assign the values accordingly
consumer_key = ""
consumer_secret = ""
access_token = ""
access_token_secret = ""
  
# authorization of consumer key and consumer secret
auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
  
# set access to user's access key and access secret 
auth.set_access_token(access_token, access_token_secret)
  
# calling the api 
api = tweepy.API(auth)
  
# list of user_ids
user_ids = [57741058, 4802800777, 1037141442]
  
# getting the users by user_ids
users = api.lookup_users(user_ids)
  
# printing the user details
for user in users:
    print("The id is : " + str(user.id))
    print("The screen name is : " + user.screen_name, end = "\n\n")