In [1]:
import tweepy

In [2]:
consumer_key = 'CQldZWCZjOPCmcuggVEYDLKb8'
consumer_secret = 'rVGwBrR5PKxZs2yIpwPIbLP6TzhARo7C4cRodrCKVFSEGTOOWi'
access_key = '1506450127057305604-XjukkZt3QPyCQ8oZTRC4qpQnglQu4u'
access_secret = 'xY7v8pWdKZaQcGGVokNQIwgwoiMSlmZlbn6nWAaytJxN2'

In [3]:
# Twitter authentication
auth = tweepy.OAuthHandler(consumer_key, consumer_secret)   
auth.set_access_token(access_key, access_secret) 
  
# Creating an API object 
api = tweepy.API(auth)

In [4]:
username_tweets = tweepy.Cursor(api.search, q="@elonmusk", tweet_mode='extended').items(5)

In [11]:
for tweet in username_tweets:
    text = tweet._json["full_text"]
    print(text)
    #using different attributes
    print(tweet.favorite_count)
    print(tweet.retweet_count)
    print(tweet.created_at)

[]

In [12]:
hashtag_tweets = tweepy.Cursor(api.search, q="#VaccinationDrive", tweet_mode='extended').items(5)

In [13]:
for tweet in hashtag_tweets:
    text = tweet._json["full_text"]
    print(text)

#VaccinationDrive Karnataka cumulatively up to 3.30pm on Nov 12 has administered 1/2 dose vaccine to 116075583 people aged 12-14; 15-17; 18-44; 45-60 &amp; 60+. Total 120625477 doses administered: @DHFWKA. @MoHFW_INDIA @sputnikvaccine @mangalurucorp @SerumInstIndia @BharatBiotech https://t.co/B7bNU5bvOo
RT @JuliaBradbury: Not long until I have my operation, grateful for my booster vaccine.
#BoosterShots #VaccinationDrive
#CovidVaccine htt‚Ä¶
RT @ankittv4: ‡§≤‡§ñ‡§®‡§ä- ‡§Ü‡§ú ‡§∏‡•á #‡§â‡§§‡•ç‡§§‡§∞‡§™‡•ç‡§∞‡§¶‡•á‡§∂ ‡§Æ‡•á‡§Ç ‡§™‡§ü‡§∞‡•Ä ‡§¶‡•Å‡§ï‡§æ‡§®‡§¶‡§æ‡§∞‡•ã‡§Ç, ‡§∞‡§ø‡§ï‡•ç‡§∂‡§æ‡§ö‡§æ‡§≤‡§ï‡•ã‡§Ç ‡§î‡§∞ ‡§∏‡§≠‡•Ä ‡§≤‡•ã‡§ó‡•ã‡§Ç ‡§ï‡•á ‡§≤‡§ø‡§è ‡§µ‡§ø‡§∂‡•á‡§∑ ‡§µ‡•à‡§ï‡•ç‡§∏‡•Ä‡§®‡•á‡§∂‡§® ‡§Ö‡§≠‡§ø‡§Ø‡§æ‡§® ‡§ï‡•Ä ‡§∂‡•Å‡§∞‡•Å‡§Ü‡§§‡•§‡§π‡§∞ ‡§ú‡§º‡§ø‡§≤‡•á ‡§ï‡•á‚Ä¶
COVID Vaccination Centre List for 12.11.2022
#VaccinationDrive #COVIDVaccine #kmcfightsagainstcorona
(2/2) https://t.co/lvfjekVb1e
COVID Vaccination Centre List for 12.11.2022
#VaccinationDrive #COVIDVaccine #kmcfightsagainstcorona
(1/2) https://t.co/oLLefV6sLY

In [15]:
new_tweets = tweepy.Cursor(api.user_timeline, screen_name="elonmusk", tweet_mode='extended').items(10)

In [17]:
list = []
for tweet in new_tweets:
    text = tweet._json["full_text"]

    refined_tweet = {'text' : text,
                    'favorite_count' : tweet.favorite_count,
                    'retweet_count' : tweet.retweet_count,
                    'created_at' : tweet.created_at}
    
    list.append(refined_tweet)

In [18]:
import pandas as pd
df = pd.DataFrame(list)
#df.to_csv('refined_tweets.csv')

In [19]:
df.head()

,text,favorite_count,retweet_count,created_at
0,@A_MrBenMitchell @RadioShack @MarioNawfal Spac...,1481,136,2022-11-13 00:39:10
1,@pauljamil @philbak1 Probably end of next week,1862,105,2022-11-13 00:38:08
2,@philbak1 My reaction to SBF was ‚Ä¶ different,15921,828,2022-11-13 00:32:01
3,@MarioNawfal Twitter at its best!,12538,966,2022-11-13 00:25:25
4,@alex_avoigt üí™üí™,9753,478,2022-11-13 00:18:14